#!/bin/bash

DOCKERCONTAINER="monodevelop-docker-container"
COUNTER=0
MAX_COUNTER=100

# check for empty docker container
while [  $COUNTER -lt $MAX_COUNTER ]; do
    # increase counter 
    let COUNTER=COUNTER+1 
    CONTAINER_NAME="$DOCKERCONTAINER$COUNTER"

    if podman ps -a --filter name=^$CONTAINER_NAME$ --format "{{.Names}}" | grep -q "^$CONTAINER_NAME$"; then
        echo "Container $CONTAINER_NAME già in uso o esistente."
        # process with this specific container already run, skip it
        echo -e "container $CONTAINER_NAME already in use"
    else
        echo -e "founded empty docker container: $CONTAINER_NAME"
        break
    fi
done

if [ $COUNTER -ge $MAX_COUNTER ]; then
    echo "Error: No one empty container found in $MAX_COUNTER attempts."
    exit 1
fi

# add this lines for proxy
# -e "HTTP_PROXY=<host>:<port>" \
# -e "HTTPS_PROXY=<host>:<port>" \

# run docker with specific docker container founded
podman run \
 --name $CONTAINER_NAME \
 --net=host \
 -it --rm \
 -e "DISPLAY=$DISPLAY" \
 -u $(id -u) \
 -v /tmp:/tmp \
 -v /opt:/opt \
 -v /home:/home:ro \
 -v /home/$USER:/home/$USER:rw \
 -v $HOME/.Xauthority:/root/.Xauthority:ro \
 -v /etc/group:/etc/group:ro \
 -v /etc/passwd:/etc/passwd:ro \
 -v /etc/shadow:/etc/shadow:ro \
 -v /etc/sudoers.d:/etc/sudoers.d:ro \
 -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
 armandob/monodevelop-docker "$@"

# Check exit code
if [ $? -ne 0 ]; then
    echo "Error on podman exec."
    exit 1
fi